# Configuración general del sitio
title: "Portafolio de Edwin Miranda"
description: "Un portafolio personal para mostrar mis proyectos y habilidades."
url: "MiPortafolio.github.io" # Cambia esto por la URL de tu sitio
baseurl: "" # Si lo alojas en una subcarpeta, pon la ruta aquí

# Configuración de redes sociales
twitter_username: "tuusuario"
github_username: "tuusuario"
linkedin_username: "tuusuario"

# Tema a utilizar
theme: jekyll-theme-hyde

# Opciones del sitio
show_downloads: true
