# Configuración general del sitio
title: "Portafolio de Edwin Miranda"
description: "Un portafolio personal para mostrar mis proyectos y habilidades."
url: "https://Edwininw.github.io" # Cambia esto por la URL de tu sitio
baseurl: "https://edwininw.github.io/MiPortafolio.github.io" # Si lo alojas en una subcarpeta, pon la ruta aquí



# Tema a utilizar
theme: jekyll-theme-hyde

# Opciones del sitio
show_downloads: true
